### ISSUE TITLE
Oopize the session

### ISSUE THREAD

**Issue by balodja** [snad-space/coniferest#100]
Proposition:
* Change `desicion_callback` to `decision_strategy` with specific abstract interface `DecisionStrategy`.
* Change `on_decision_callback` to `decision_observer` with its own corresponding interface `DecisionObserver`.

Something like that:
```python
class DecisionStrategy(ABC):
    @abstractmethod
    def decide(metadata: np.ndarray, data: np.ndarray, session: Session) -> Label:
        pass


class DecisionObserver(ABC):
    @abstractmethod
    def observe(metadata: np.ndarray, data: np.ndarray, session: Session, decision: Label) -> None:
        pass
```

That will:
* separate different parts of the state in the clear way,
* make the purpose of callbacks and their look more obvious to user,
* moreover we may move them out of the `Session.__init__` to `setDecisionStrategy` and `addDecisionObserver` to relieve the constructor a bit.

Is that reasonable? @matwey @hombit

**Comment by hombit** [comment]
I don't support an idea of making a base class with a single method which users must inherit from. While I agree that it makes user's code more self-descriptive, it also makes it longer and harder to write. My feeling that we rarely see such interfaces in Python libraries, which usually prefer functions over classes. Moreover I don't think that people of science will find it more obvious.

Having long __init__ is fine, look at scikit or other ML libraries like PyTorch Lightning.

However, we should rename arguments if current names are unclear.
