### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by hombit** [snad-space/coniferest#13]

**Comment by balodja** [comment]
Issue dependencies:
* #11
* #9
* #17

**Comment by balodja** [comment]
[Uploaded to pypi](https://pypi.org/project/coniferest/).

@hombit , Konstantin, could you check the `pip install coniferest`, please?

**Comment by balodja** [comment]
Ah, I see, it doesn't work. Damn those extensions.

**Comment by balodja** [comment]
@hombit , please, check again. Should work now.

**Comment by hombit** [comment]
It works, thank you!
